In [1]:
import numpy as np

## Mathematics For Machine Learning

A notebook for learning the mathematics for machine learning via python code

#### Matrices

Matrix Addition

The sum of two matrices $A \in R^{m,n}, A \in R^{m,n}$ is defined as the element-wise sum

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A + B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

Matrix Multiplication

The product of two matrices $A \in R^{m, n}, B \in R^{n, k}$ is $C = AB \in R^{n,k}$ 

In [3]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1]
])
B = np.array([
    [0, 2],
    [1, -1],
    [0, 1]
])

(A @ B, B @ A)

(array([[2, 3],
        [2, 5]]),
 array([[ 6,  4,  2],
        [-2,  0,  2],
        [ 3,  2,  1]]))

Identitty Matrix

In [4]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Associativity Property

In [5]:
# m,n
A = np.array([
    [2, 3],
    [3, 2]
])
# n,p
B = np.array([
    [2, 3, 1],
    [3, 2, 1]
])
# p,q
C = np.array([
    [2, 3],
    [3, 2],
    [5, 1]
])

D1 = (A @ B) @ C
D2 = A @ (B @ C)
np.array_equiv(D1, D2)

True

Distributivity Property

In [6]:
# m,n
A = np.array([
    [2, 3],
    [3, 2]
])
B = np.array([
    [3, 1],
    [2, 1]
])

# n,p
C = np.array([
    [2, 3, 1],
    [3, 2, 1],
])
D = np.array([
    [4, 2, 3],
    [8, 3, 2],
])


print(np.array_equiv((A + B) @ C, (A @ C) + (B @ C)))
print(np.array_equiv(A @ (C + D), (A @ C) + (A @ D)))

True
True


Inverse Matrix

