In [1]:
from tinygrad.tensor import Tensor

In [2]:
x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0, 0, -2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()

In [4]:
print(x.grad.numpy()) # dz/dx

[[ 2.  2.  2.]
 [ 0.  0.  0.]
 [-2. -2. -2.]]


In [5]:
print(y.grad.numpy()) # dz/dy

[[1. 1. 1.]]
